### ISSUE TITLE
Grajenje URL-jev in predloge

### ISSUE THREAD

**Issue by jaanos** [BlackPhoenixSlo/projektna-naloga-Covid-19#3]
Svetujem, da URL-je gradita s funkcijo `url` (na vsaj enem mestu to že počneta), s čimer bosta omogočila, da projekt teče tudi na Binderju. Za več podrobnosti si poglejta MatejRojec/Gamma#1.

Vidim tudi, da imata v vsaki predlogi celotno ogrodje - tj., osnovna koda HTML se vama ponavlja, tako da bi bilo kakršnokoli spremembo narediti na vseh predlogah. Imata sicer pripravljeno tudi skupno osnovo `osnova.html` - v ostalih predlogah jo vključite z `rebase`, da vama osnove ni potrebno ponavljati. Poglejta si, kako je to urejeno na vzorčnem projektu.

**Comment by tinmarkon** [comment]
Popravil sem vse redirecte da delajo preko funkcije url. Popravil sem tudi na htmljih.
