### ISSUE TITLE
Zakljucen projekt

### ISSUE THREAD

**Issue by tinmarkon** [BlackPhoenixSlo/projektna-naloga-Covid-19#4]
Ker Jaka nima veliko časa v tem izpitnem obdobju, sem projekt zaključil in ga pripravil za oddajo. Zanima me ali je možno da projekt potem jaz še malo nadgradim in grem kasneje na ustni izpit?

**Comment by majbc1999** [comment]
Živjo! Projekt se mi zdi v redu. Sicer sem naletel na težavo, ko sem se želel registrirati:

```python
Traceback (most recent call last):
  File "c:\Users\majbc\Namizje\Sola\MAGISTERIJ\2. semester\Osnove podatkovnih baz\Projekti\projektna-naloga-Covid-19\bottle.py", line 868, in _handle
    return route.call(**args)
  File "c:\Users\majbc\Namizje\Sola\MAGISTERIJ\2. semester\Osnove podatkovnih baz\Projekti\projektna-naloga-Covid-19\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "c:\Users\majbc\Namizje\Sola\MAGISTERIJ\2. semester\Osnove podatkovnih baz\Projekti\projektna-naloga-Covid-19\bottleext.py", line 15, in decorator
    return callback(*largs, **kwargs)
  File "c:/Users/majbc/Namizje/Sola/MAGISTERIJ/2. semester/Osnove podatkovnih baz/Projekti/projektna-naloga-Covid-19/covid.py", line 266, in register_post
    id = get_id_from(emso)
  File "c:/Users/majbc/Namizje/Sola/MAGISTERIJ/2. semester/Osnove podatkovnih baz/Projekti/projektna-naloga-Covid-19/covid.py", line 84, in get_id_from
    return cur.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```
Nato sem se prijavil z admin računom in vidim, da sta ostale stvari dobro naredila. Dodata lahko še *binder* (orodje, ki zažene repozitorij v oblaku): to naredita zelo hitro in sicer podobno kot [v vzorčnem repozitoriju](https://github.com/jaanos/OPB-bottle) (glej mapo `binder` in nato povezavo na binder v `README`). 

Ko popravita problem pri registraciji in dodata binder, mi napišita, da še enkrat pogledam, če vse dela, in vama v tem primeru potrdim projekt. Glede ločenih zagovorov sem vprašal Janoša in vama sporočim, ko mi odgovori.

**Comment by tinmarkon** [comment]
Popravil sem problem pri registraciji, aplikacija preverja ali je bodoči uporabnik v bazi prebivalstva, zato pa vrne napako. Zdaj to tudi izpiše.

**Comment by tinmarkon** [comment]
Problem pri binderju imam pri 'dinamicnih' urljih, kjer je parameter del linka. Nevem kako vkljuciti ta parameter pri generiranju linka. Zdaj je urejeno takole in ne dela.

`href="{{url('remove_post(emso)')}}` 

pri čemer je emšo parameter, ki ga dobi iz seznama.

To sem kopiral iz htmlja `remove_pacient`

**Comment by jaanos** [comment]
Če želita podati še parameter, ga podasta kot poimenovan parameter funkciji `url`, npr. `url('remove_post', x=emso)`.

**Comment by tinmarkon** [comment]
Super, najlepša hvala. Projekt je zdaj zaključen in pripravljen za oddajo.

**Comment by majbc1999** [comment]
Super, sem še enkrat preveril in mi je vse delovalo. @jaanos, prosim, da jima dodaš projekt na repozitorij predmeta. Lahko se torej z @alenFMF domenita za termin zagovora. Če bosta do takrat še kaj spreminjala, javita, da se posodobi povezava.

> Zanima me ali je možno da projekt potem jaz še malo nadgradim in grem kasneje na ustni izpit?

Glede tega se morata posebej dogovoriti s prof. Orbanićem.

**Comment by jaanos** [comment]
Sem dodal povezavo do projekta na repozitorij predmeta. Kot rečeno, če bosta do zagovorov še kaj spreminjala, mi javita, da posodobim povezavo.

Sicer pa svetujem še, da v `README.md` dodasta navodila za prijavo (tj., uporabniško ime in geslo za administratorja in še kakšnega uporabnika, da se lahko to takoj preizkusi). Poleg tega sem opazil, da odjava ne deluje na Binderju.

**Comment by BlackPhoenixSlo** [comment]
Bi se lahko zmenila za zagovor, Tin bi prišel malo kasneje, ker ima še
nekaj izpitov, jaz pa zdaj ker letim 17.6. v ameriko. Je možno?

Lep pozdrav, Jaka

**Comment by tinmarkon** [comment]
Posodobil sem `README.md` tako da ima zdaj vse potrebne podatke in uredil tudi povezavo za odjavo.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
